### ISSUE TITLE
About Lilim

### ISSUE THREAD

**Issue by blw1234** [Cosetto/Visual-novel-archive-tools#1]
May I ask if you have any way to pack Lilim's scr.aos
I encountered a problem while packaging the  LiLiM DARKNESS new game
This is a game[https://vndb.org/v38875](url)

**Comment by Cosetto** [comment]
What's the problem you encounter?

**Comment by blw1234** [comment]
[scr2.zip](https://github.com/Cosetto/Visual-novel-archive-tools/files/11134992/scr2.zip)
This is my repackaged script file,extra Have a problem
![image](https://user-images.githubusercontent.com/120999489/229419379-7b33be6f-9776-44be-b03f-c704c60ddd22.png)

The same problem would occur if I repackaged without making any modifications

**Comment by Cosetto** [comment]
Sorry for late reply, try this [GARbro](https://github.com/satan53x/GARbro/releases)
