### ISSUE TITLE
Extracting some file

### ISSUE THREAD

**Issue by RaohPresident** [Cosetto/Visual-novel-archive-tools#2]
Hi guys, 

Regarding the visual novel text extraction, I am facing the same issue as you on Gore Screaming Show and the 082.spt file. 
So I would like to ask if you solved that issue or manage to extract the text from this file?

https://github.com/arcusmaximus/VNTranslationTools/issues/87#issuecomment-1312653650

Thanks in advance
Raoh

**Comment by Cosetto** [comment]
Download Japanese version and get 082.spt from it

**Comment by RaohPresident** [comment]
Thanks,
My plan is to translate the english version a french one, from the trad I manage to extract all the other file but on the english one I get the startIndex error.
But I do not understand why the english version does not work
Many thanks

**Comment by Cosetto** [comment]
Use [this](https://github.com/eliasstein/Old-SystemNNN-extractor) to extract English text from 082.spt and paste it on vntextpatch's script.

**Comment by RaohPresident** [comment]
Thanks a lot Cosetto!
