### ISSUE TITLE
Reverse sysgrp results | BGI\Ethornell Engine

### ISSUE THREAD

**Issue by Walkedharmony** [Cosetto/Visual-novel-archive-tools#4]
I used [this](https://github.com/xupefei/BGIKit) to convert a bmp file to arc format but the resulting image was reversed 180

I also used [this](https://github.com/xmoezzz/BGITool) to change it the result is still the same.

![Screenshot 2024-03-05 093830](https://github.com/Cosetto/Visual-novel-archive-tools/assets/157404664/443c3bc2-a71f-4514-857d-1d10e50b7a4a)
![Screenshot 2024-03-05 094428](https://github.com/Cosetto/Visual-novel-archive-tools/assets/157404664/c729bf46-708e-4b24-a639-b6f5e8823f1a)

**Comment by Cosetto** [comment]
Well, you can leave it as bmp and delete .bmp extension, the engine will read it.
Or you can [my fork](https://github.com/Cosetto/BGIKit/blob/master/SysgrpConverter/Program.cs) version
![image](https://github.com/Cosetto/Visual-novel-archive-tools/assets/81801486/3579d370-2744-45e5-ba1c-4dfb0956f3a2)

**Comment by Walkedharmony** [comment]
> Nah, Anda bisa membiarkannya sebagai bmp dan menghapus ekstensi .bmp, mesin akan membacanya. Atau Anda dapat versi [garpu saya](https://github.com/Cosetto/BGIKit/blob/master/SysgrpConverter/Program.cs) ![citra](https://private-user-images.githubusercontent.com/81801486/310098082-3579d370-2744-45e5-ba1c-4dfb0956f3a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzg4NjksIm5iZiI6MTcwOTYzODU2OSwicGF0aCI6Ii84MTgwMTQ4Ni8zMTAwOTgwODItMzU3OWQzNzAtMjc0NC00NWU1LWJhMWMtNGRmYjA5NTZmM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTgxYWM2NDJhNzgwMTU4MjExNTg3ZWFkOTZlNjUwZTdmMjk3Njg0ZWFjMmNhMzMwMzQ5NThkMDdhOTNmYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QUDhshalx7YT219-XsYDfl8jC8MJNxXp_rmAZRTLYmQ)

It's worked well, thank you.

Can I ask about the _.bp assembly?

As you explained [here](https://github.com/arcusmaximus/EthornellTools/issues/4#issuecomment-1166412073), it says bpdis will produce a file with the extension .bpd but the result is like this
![Screenshot 2024-03-05 164050](https://github.com/Cosetto/Visual-novel-archive-tools/assets/157404664/dd6f4ab6-af3b-45b0-959d-22b4e269808f)

I will put the test file here
[yesnownd.zip](https://github.com/Cosetto/Visual-novel-archive-tools/files/14494799/yesnownd.zip)

Thank you for your time

**Comment by Cosetto** [comment]
> Note that the code is from 6 years ago so the bpop.py maybe missing new opcode from newer games.

This is the reason

**Comment by Walkedharmony** [comment]
> > Perhatikan bahwa kode tersebut berasal dari 6 tahun yang lalu sehingga bpop.py mungkin kehilangan opcode baru dari game yang lebih baru.
> 
> Inilah alasannya

can't it be updated by itself? What I saw in the _.bp file was that there was text outside the image, so I wanted to try it.

**Comment by Cosetto** [comment]
> can't it be updated by itself?

Nope. Looks like it's the latest version of BGI, even BgiDisassembler doesn't work.

**Comment by Walkedharmony** [comment]
> > Tidak bisakah itu diperbarui dengan sendirinya?
> 
> Nope. Sepertinya ini adalah versi terbaru dari BGI, bahkan BgiDisassembler tidak berfungsi.

I once tried changing it directly with a hex editor but the result was like this😅
![Screenshot 2024-03-05 193348](https://github.com/Cosetto/Visual-novel-archive-tools/assets/157404664/927d74d3-0ef7-4fde-a862-89b3b031f94a)

**Comment by Cosetto** [comment]
It's difficult to edit string in ._bp files with hex editor, you will need to calculate a little bit to fit the string in. It's been a long time since I did it, so I can't remember much.

**Comment by Walkedharmony** [comment]
> Sulit untuk mengedit string dalam file ._bp dengan editor hex, Anda perlu menghitung sedikit agar sesuai dengan string. Sudah lama sejak saya melakukannya, jadi saya tidak dapat mengingat banyak.

Well, I'll try various things for that

**Comment by Walkedharmony** [comment]
> It's difficult to edit string in ._bp files with hex editor, you will need to calculate a little bit to fit the string in. It's been a long time since I did it, so I can't remember much.

It seems that this engine is a bit difficult, the only things that can be modified in this engine are scenarios and images, it cannot include images such as game titles, chapter titles and help texts.

![Screenshot 2024-03-06 082827](https://github.com/Cosetto/Visual-novel-archive-tools/assets/157404664/5655a425-bf61-4a38-81dc-2d456f8836a9)


Unless it can find new opcodes for the latest BGI/Ethornell version.

**Comment by Cosetto** [comment]
Actually you can use this
[bp_tool.zip](https://github.com/Cosetto/Visual-novel-archive-tools/files/14507553/bp_tool.zip)
It will process the text only

**Comment by Walkedharmony** [comment]
> Actually you can use this [bp_tool.zip](https://github.com/Cosetto/Visual-novel-archive-tools/files/14507553/bp_tool.zip) It will process the text only

Yes, I have tried it, it can only change it to text but can't assemble it back to the original file

**Comment by Cosetto** [comment]
> > Actually you can use this [bp_tool.zip](https://github.com/Cosetto/Visual-novel-archive-tools/files/14507553/bp_tool.zip) It will process the text only
> 
> Yes, I have tried it, it can only change it to text but can't assemble it back to the original file

By that you mean you can't insert the text back? Or you can insert the text back, but the new file pop error?

**Comment by Walkedharmony** [comment]
> > > Sebenarnya Anda dapat menggunakan [bp_tool.zip](https://github.com/Cosetto/Visual-novel-archive-tools/files/14507553/bp_tool.zip) ini Ini akan memproses teks saja
> > 
> > 
> > Ya, saya sudah mencobanya, itu hanya dapat mengubahnya menjadi teks tetapi tidak dapat merakitnya kembali ke file aslinya
> 
> Maksud Anda, Anda tidak dapat memasukkan teks kembali? Atau Anda dapat memasukkan teks kembali, tetapi kesalahan pop file baru?

can't assemble back to _.bp after becoming text

**Comment by Walkedharmony** [comment]
Well maybe for every VN that uses BGI, the machine always needs new opcodes for it.

![Screenshot 2024-03-07 231116](https://github.com/Cosetto/Visual-novel-archive-tools/assets/157404664/37d18fa6-83c7-48f7-a881-b99439d1717b)
