### ISSUE TITLE
Want Some help!!!

### ISSUE THREAD

**Issue by subaru471171** [Cosetto/Visual-novel-archive-tools#5]
First of all i apologize , as i want some help regarding the VNtranslationTool as there is no way to post a issue there. i anted to ask help regarding extracting Amusecraft/softpal script files . its showing error like this

C:\Users\arkad\OneDrive\Downloads\Miscalleneous\ArtemisTranslationTools\VNTextPatch>VNTextPatch extractlocal C:\Users\arkad\OneDrive\Downloads\Miscalleneous\ArtemisTranslationTools\Input\SCRIPT.SRC C:\Users\arkad\OneDrive\Downloads\Miscalleneous\ArtemisTranslationTools\intermidiate\script.json
Index was outside the bounds of the array.

here are the files
[data.zip](https://github.com/user-attachments/files/17993527/data.zip)

How can i resolve this issue

**Comment by Cosetto** [comment]
vntextpatch extractlocal input\script.src script\script.json
